### ISSUE TITLE
This does not work at all

### ISSUE THREAD

**Issue by warmaster2143** [mklements/OLED_Stats_Docker#9]
Hi followed every step and it does not work at all and my screen cables are connected correctly

**Comment by warmaster2143** [comment]
it seems like the container is unable to start in te first place i get this error when i try to restart it in Portainer

Failure
Container 19137afe390f9b0b707c0386151f298e3172caaac94800addd406235756a0588 is restarting, wait until the container is running

**Comment by warmaster2143** [comment]
chip_id = detector.chip.id
              ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/adafruit_platformdetect/chip.py", line 425, in __getattr__
    if self.id == attr:
       ^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/adafruit_platformdetect/chip.py", line 425, in __getattr__
    if self.id == attr:
       ^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/adafruit_platformdetect/chip.py", line 425, in __getattr__
    if self.id == attr:
       ^^^^^^^
  [Previous line repeated 974 more times]
  File "/opt/venv/lib/python3.11/site-packages/adafruit_platformdetect/chip.py", line 159, in id
    self._chip_id = self._linux_id()
                    ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/adafruit_platformdetect/chip.py", line 297, in _linux_id
    hardware = self.detector.get_cpuinfo_field("Hardware")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/adafruit_platformdetect/__init__.py", line 43, in get_cpuinfo_field
    with open("/proc/cpuinfo", "r", encoding="utf-8") as infile:
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):

**Comment by xnlkox** [comment]
Bump

**Comment by henkiewie** [comment]
The docker container stopped working. I can not find an older version or any version on docker hub to go back to python 3.10?
